In [1]:
#모듈 불러오기
import numpy as np

In [2]:
#버전 확인
np.__version__

'1.20.3'

In [4]:
#배열 확인 함수
def printinfo(array):
    print("shape : {}, dimension : {}, dtype: {}". format(array.shape, array.ndim, array.dtype))

## Numpy 배열(Array) 생성하기
- 1) array 함수를 사용하여 배열 생성하기
- 2) zeros, ones, empty 함수를 사용하여 배열 생성하기
- 3) arange 함수를 사용하여 배열 생성하기

### 1) array 함수를 사용하여 배열 생성하기
- 1차원 배열 생성하기

In [6]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [7]:
array.shape
#원소가 5개

(5,)

In [8]:
array.ndim
#차원을 보여준다

1

In [9]:
array.dtype
#전부 int 32bit타입이다

dtype('int32')

In [10]:
printinfo(array)

shape : (5,), dimension : 1, dtype: int32


- 2차원 배열 생성하기

In [12]:
list = [[1,2,3], [4,5,6]]
array2 = np.array(list, dtype = float)
array2

#2행 3열로 구성

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
printinfo(array2)

shape : (2, 3), dimension : 2, dtype: float64


- 3차원 배열 생성하기

In [18]:
array3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]], dtype=float)
array3

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [19]:
printinfo(array3)

shape : (2, 2, 3), dimension : 3, dtype: float64


### 2) zeros, ones, empty 함수를 사용하여 배열 생성하기

- zeros

In [20]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- ones

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

- empty

In [24]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219035e-306],
       [1.06810404e-306, 6.23058028e-307, 2.22522597e-306,
        1.33511969e-306],
       [1.37962320e-306, 9.34604358e-307, 9.79101082e-307,
        1.78020576e-306],
       [1.69119873e-306, 2.22522868e-306, 1.24611809e-306,
        8.06632139e-308]])

### 3) arange 함수를 사용하여 배열 생성하기

In [25]:
array4 = np.arange(10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
printinfo(array4)

shape : (10,), dimension : 1, dtype: int32


In [31]:
array5 = np.arange(0,11,2)
array5

array([ 0,  2,  4,  6,  8, 10])

## ndarray 배열의 모양, 차수, 데이터 타입 확인

In [33]:
## shape, ndim, dtype 함수를 사용항 모양 차원 데이터타입 확인하기

arr = np.array([[1,2,3],
               [4,5,6]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


## ndarray 타입 변환 : astype() 함수 이용

- 정수형 데이터 배열을 실수형 데이터 배열로 변환하기

In [34]:
arr_int = np.array([1,2,3,4,5])

In [35]:
arr_int.dtype

dtype('int32')

In [36]:
arr_float = arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

- 문자형 데이터 배열을 정수형 데이터 배열로 변환하기

In [37]:
arr_str = np.array(['1', '2', '3']) #문지형 데이터 배열 생성

In [38]:
arr_str.dtype

dtype('<U1')

In [39]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [40]:
arr_int

array([1, 2, 3], dtype=int64)

### ndarray의 차원과 크기를 변경 : reshape()

- 1차원 --> 2차원으로 reshape

In [42]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr2 = arr1.reshape((5, 2))
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- 2차원 이상 배열을 1차원으로 만들기

In [44]:
arr2.reshape(-1) #reshape() 메서드 이용

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr2.flatten() #flatten()메서드 이용
#flatten은 그냠 어떤 차원이든 전부 1차원으로 강제 변환한다

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- reshape(-1,1) or reshape(-1)

In [48]:
arr1 = np.arange(5)

In [49]:
arr2 = arr1.reshape(-1,1)
arr2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [51]:
arr.ndim
#2차원이 된걸 볼 수 있다

2

In [52]:
arr3 = arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4])

In [53]:
arr3.ndim

1

## ndarray의 데이터 선택하기 : 인덱싱(indexing)

### 단일 값 추출
- 1차원 ndarray 인덱싱

In [56]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[3]

4

In [58]:
arr[-1]

9

In [59]:
arr[-2]

8

- 2차원 ndarray 인덱싱

In [61]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr[0,0]

1

In [63]:
arr[0,1]

2

### 슬라이싱(slicing)

In [65]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[0:3]

array([1, 2, 3])

In [67]:
arr[:3]

array([1, 2, 3])

- 2차원 ndarray의 슬라이싱

In [68]:
arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [70]:
arr[1:3, 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [71]:
arr[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray값을 반환

In [74]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[[2, 4, 7]]

array([3, 5, 8])

- 2차원의 ndarray의 팬시 인덱싱

In [77]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr[[0,1], 2]

array([3, 6])

### 불린 인덱싱
- 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 ndarray 값을 반환
- ndarray내에서 5보다 큰 값을 추출하고자 한다면?

In [79]:
#불린 인덱싱을 사용하지 않는 경우
arr = np.arange(1, 10)
target = []

for i in range(0, 9):
    if arr[i] > 5:
        target.append(i)

result = np.array(target)
result

array([5, 6, 7, 8])

- 불린 인덱싱

In [80]:
arr = np.arange(1, 10)
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [81]:
arr[arr>5]

array([6, 7, 8, 9])

In [83]:
arr[~(arr>5)]
#거짓인 부분만 가져온다

array([1, 2, 3, 4, 5])

### ndarray 배열의 연산
- 1) 기본 연산자와 함수를 통해 배열 연산
    - Numpy 배열의 기본 연산자 : (+, -, *, /) 또는 함수 (add_덧셈, subtract_뺄셈, multiply_곱셈, divide_나눗셈)
- 2) dot 함수를 사용하여 행렬의 곱 계산하기

In [85]:
## 배열 연산
arr1 = np.array([[1,2],
                [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

In [86]:
arr1 +  arr2

array([[ 6,  8],
       [10, 12]])

In [87]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [88]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

- dot 연산

In [89]:
arr1 = np.array([[1, 2],
                [3, 4]])

arr2 = np.array([[5, 6],
                [7, 8]])

In [90]:
arr1.shape

(2, 2)

In [91]:
arr2.shape

(2, 2)

In [92]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [93]:
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

### ndarray 배열의 선형 대수 연산 - 전치 행렬

In [95]:
arr = np.array([1,2,3,4]).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [96]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

In [98]:
arr = np.array([1,2,3,4,5,6]).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
np.transpose(arr)

array([[1, 3, 5],
       [2, 4, 6]])